import Link from "next/link";
import "app/globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <nav className="h-14 w-screen border border-black flex items-center justify-center list-none gap-2">
          <a href="/">
            <li>Home</li>
          </a>
          <Link href="/other">
            <li>Other</li>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
